spring.datasource.url=jdbc:mysql://localhost:3306/log_analyzer
spring.datasource.username=root
spring.datasource.password=dk1306

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true